// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdPICh7B_qO8PBMW70gl6BxhtYJwkszjY',
    appId: '1:907203013942:web:d3e0809dba2e5e41a61797',
    messagingSenderId: '907203013942',
    projectId: 'bsgi-counter-shirt',
    authDomain: 'bsgi-counter-shirt.firebaseapp.com',
    storageBucket: 'bsgi-counter-shirt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJcXz45tkKhbgfSyGnE4oSlDzlrLehhFc',
    appId: '1:907203013942:android:9ad92bdd80139eb8a61797',
    messagingSenderId: '907203013942',
    projectId: 'bsgi-counter-shirt',
    storageBucket: 'bsgi-counter-shirt.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdPICh7B_qO8PBMW70gl6BxhtYJwkszjY',
    appId: '1:907203013942:web:5b6a8a94057d34c6a61797',
    messagingSenderId: '907203013942',
    projectId: 'bsgi-counter-shirt',
    authDomain: 'bsgi-counter-shirt.firebaseapp.com',
    storageBucket: 'bsgi-counter-shirt.firebasestorage.app',
  );

}